---
driver:
  name: vagrant
  network:
    - ["private_network", {type: "dhcp"}]
  synced_folders:
    - ["../../..", "/vagrant", "disabled: false, type: :nfs"]

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  environments_path: environments
  client_rb:
    environment: dev

platforms:
  - name: centos-6.6
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[devphpstack::default]
    attributes:
