name 'devphpstack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures devphpstack'
long_description 'Installs/Configures devphpstack'
version '0.1.0'
