name             'devphpstack'
maintainer       'Purch'
maintainer_email 'dsmith@purch.com'
license          'all_rights'
description      'Installs/Configures devphpstack'
long_description 'Installs/Configures devphpstack'
version          '0.1.3'

depends 'phpstack', '~> 4.0.2'
depends 'mysql2_chef_gem', '~> 1.0'
depends 'composer', '~> 2.1'
