name             'devphpstack'
maintainer       'Purch'
maintainer_email 'dsmith@purch.com'
license          'all_rights'
description      'Installs/Configures devphpstack'
long_description 'Installs/Configures devphpstack'
version          '0.1.2'

depends 'phpstack', '~> 4.0.2'
depends 'platformstack', '>= 3.1.4'
depends 'stack_commons', '>= 0.0.49'
depends 'mysql2_chef_gem', '~> 1.0'
depends 'database', '= 3.1.0'
depends 'composer', '~> 2.1'
depends 'windows', '~> 1.37.0'
depends 'percona', '= 0.15.5'
